apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: teleport-insecure-transport
  namespace: kube-system # <-- MUDANÇA CRUCIAL PARA O TRAEFIK DO K3S ENXERGAR
spec:
  insecureSkipVerify: true
