apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia-headers
  namespace: authelia # Ajuste para o namespace onde o Authelia está rodando
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    frameDeny: true
    sslRedirect: true
    stsPreload: true
    stsSeconds: 31536000
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Method: ""
