apiVersion: v2
name: infra-stack
version: 1.0.0
description: Helm Chart guarda-chuva para a infraestrutura do cluster


dependencies:
  - name: grafana
    version: "12.7.2"
    repository: "https://grafana-community.github.io/helm-charts"
  #- name: loki
  #  version: "^18.5.2" 
  #  repository: https://grafana-community.github.io/helm-charts
  #- name: tempo
  #  version: 1.18.0
  #  repository: https://grafana-community.github.io/helm-charts
  #- name: minio
  #  version: "5.4.0" # Ou outra versão estável da Bitnami/MinIO
  #  repository: https://charts.min.io/