# =========================================================================
# Configurações do Grafana
# =========================================================================
grafana:
  domain: monitor.devtechdojo.com.br
  port: 80
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://192.168.15.210:3100
          jsonData:
            derivedFields:
              - datasourceUid: tempo
                matcherRegex: '(?:trace_id|traceId)="?(\w+)"?'
                name: TraceID
                url: '$${__value.raw}'
        - name: Tempo
          type: tempo
          access: proxy
          url: http://192.168.15.210:3200
          uid: tempo
        # Adicionado: Fonte de dados do Prometheus
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://192.168.15.210:9090
          jsonData:
            httpMethod: POST
            # Vincula o Prometheus ao Loki para você pular de métricas para logs facilmente
            exemplarTraceIdDestinations:
              - datasourceUid: tempo
                name: TraceID