# Configurações do Loki
loki:
  auth_enabled: false
  deploymentMode: SingleBinary
  deploymentStructure:
    singleBinary:
      replicas: 1
  # Define que o armazenamento será local
  commonConfig:
    replication_factor: 1
    path_prefix: /var/loki

  storage:
    type: filesystem
    # Correção do erro: Declara os buckets exigidos pelo template do Helm
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin

  storage_config:
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules

# Configurações do Tempo
tempo:
  storage:
    trace:
      backend: local

grafana:
  domain: monitor.devtechdojo.com.br
  port: 80
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://{{ .Release.Name }}-loki.monitoring.svc.cluster.local:3100
          jsonData:
            derivedFields:
              - datasourceUid: tempo
                matcherRegex: '(?:trace_id|traceId)="?(\w+)"?'
                name: TraceID
                url: '$${__value.raw}'
        - name: Tempo
          type: tempo
          access: proxy
          url: http://{{ .Release.Name }}-tempo.monitoring.svc.cluster.local:3100
          uid: tempo
