apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gite-ingressroute 
  namespace: argocd
spec:
  entryPoints:
    - websecure # Ouve na porta 443 do Traefik
  routes:
    - match: Host(`repo.devtechdojo.com.br`)
      kind: Rule
      services:
        - name: gitea # Nome do Service do Gitea gerado pelo Helm
          port: 3000  # Porta padrão do container/service do Gitea