apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-secret
  namespace: kube-system
type: Opaque
data:
  # O token precisa estar codificado em Base64
  # No Linux/macOS, use: echo -n "seu-token-aqui" | base64
  cloudflare-token: ZXlKaElqb2lPR1E0WkRKaE5EWmpNVEE0TTJRMll6UmtOemcyTlRFMFlXSmhNbUpsTVRnaUxDSjBJam9pWWpWaE4yVTJPR1F0WVRSbVppMDBOV05qTFRnME1ESXROamszWldNNE1HSmxNelZoSWl3aWN5STZJazVYVG0xYVIwMHlUbXByZEU5VVFYZE5RekF3V1hwQmQweFhTVFJOYW1OMFRsZFpNRTE2V1RGWlYxSnRUVzFTYXlKOQ==

