apiVersion: v1
kind: Secret
metadata:
  name: tunnel-token
stringData:
  token: eyJhIjoiOGQ4ZDJhNDZjMTA4M2Q2YzRkNzg2NTE0YWJhMmJlMTgiLCJ0IjoiYjVhN2U2OGQtYTRmZi00NWNjLTg0MDItNjk3ZWM4MGJlMzVhIiwicyI6Ik5XTm1aR00yTmprdE9UQXdNQzAwWXpBd0xXSTRNamN0TldZME16WTFZV1JtTW1SayJ9
