apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argocd
spec:
  project: default
  source:
    chart: authelia
    repoURL: https://charts.authelia.com
    targetRevision: 0.11.22
    helm:
      values: |
        config:
          theme: light
          session:
            cookies:
              - domain: devtechdojo.com.br
          authentication_backend:
            ldap:
              enabled: false
            file:
              enabled: true
              path: /config/users_database.yml
              watch: true
          storage:
            local:
              enabled: true
          notifier:
            filesystem:
              enabled: true
          access_control:
            default_policy: one_factor
            rules: []

        # 3. Referência à sua Secret de senhas/chaves do sistema
        secret:
          existingSecret: authelia-secrets

        # 4. Injeção do arquivo de usuários criado na Secret authelia-users
        pod:
          extraVolumes:
            - name: users-database
              secret:
                secretName: authelia-users
          extraVolumeMounts:
            - name: users-database
              mountPath: /config/users_database.yml
              subPath: users_database.yml


  destination:
    server: https://kubernetes.default.svc
    namespace: authelia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true