apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argocd
spec:
  project: default
  source:
    chart: authelia
    repoURL: https://charts.authelia.com
    targetRevision: 0.11.22
    helm:
      values: |
        configMap:
          session:
            cookies:
              - domain: auth.devtechdojo.com.br
          authentication_backend:
            file:
              # Aponta para o caminho onde vamos montar o arquivo usando os volumes do pod
              path: /config/users_database.yml
              watch: true
          storage:
            local:
              enabled: true
          notifier:
            filesystem:
              enabled: true

        # Força o Chart a usar a sua secret existente para as variáveis de ambiente globais
        secret:
          existingSecret: authelia-secrets

        # Injeta o arquivo usando o bloco de customização do Pod nativo do Chart
        pod:
          extraVolumes:
            - name: users-database
              secret:
                secretName: authelia-users
          extraVolumeMounts:
            - name: users-database
              mountPath: /config/users_database.yml
              subPath: users_database.yml

  destination:
    server: https://kubernetes.default.svc
    namespace: authelia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true