apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argocd
spec:
  project: default
  
  source:
    chart: authelia
    repoURL: https://charts.authelia.com
    targetRevision: 0.11.20
    
    helm:
      values: |
        # Configurações aceitas estritamente dentro do ConfigMap nativo do Chart
        configMap:
          theme: dark
          
          # Correção 1: Ajuste do JWT e Encryption Key exigidos pelo erro de storage
          jwt_secret: "substitua_por_um_segredo_longo_e_aleatorio_jwt"
          storage:
            encryption_key: "substitua_por_um_segredo_longo_e_aleatorio_storage"
            local:
              path: /config/db.sqlite3
          
          # Correção 2: Ajuste de sessões obrigatórias
          session:
            secret: "substitua_por_um_segredo_longo_e_aleatorio_session"
            cookies:
              - domain: devtechdojo.com.br
                subdomain: auth
                default_redirection_url: https://devtechdojo.com.br
          
          # Correção 3: Inclusão de regras para matar o erro de 'access_control'
          access_control:
            default_policy: 'deny'
            rules:
              - domain: '*.devtechdojo.com.br'
                policy: 'two_factor'

          # Correção 4: Backend de autenticação apontando para o arquivo criado abaixo
          authentication_backend:
            password_reset:
              disable: true
            file:
              path: /config/users_database.yml

          # Correção 5: Notificador local para matar o erro de 'notifier'
          notifier:
            filesystem:
              filename: /config/notification.txt

        # Criação do arquivo de usuários montado automaticamente pelo Helm na pasta /config
        files:
          users_database.yml: |
            users:
              admin:
                disabled: false
                displayname: "Administrador"
                password: "$argon2id$v=19$m=65536,t=3,p=4$bXlzYWx0c3RyaW5n$O3E0OStpMmE5cTJ1M2k0bzVpNm83dTg" # Senha padrão: authelia
                email: admin@devtechdojo.com.br
                groups:
                  - admins

        persistence:
          enabled: true
          size: 2Gi

        ingress:
          enabled: true
          className: "traefik"

  destination:
    server: https://kubernetes.default.svc
    namespace: authelia

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
