apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argocd
spec:
  project: default
  source:
    chart: authelia
    repoURL: https://repo.helmforge.dev
    targetRevision: 1.5.11
    helm:
      values: |
        config:
          server:
            buffers:
              read: 16384  # Aumenta de 4096 para 16KB
              write: 16384

          session:
            cookies:
              - domain: 'devtechdojo.com.br'
                authelia_url: 'https://auth.devtechdojo.com.br'

          access_control:
            default_policy: deny
            rules:
              - domain: ['trace.devtechdojo.com.br',  'code.devtechdojo.com.br']
                policy: two_factor
              - domain: ['draw.devtechdojo.com.br', 'homepage.devtechdojo.com.br' , 'devtechdojo.com.br']
                policy: one_factor

        # Configuração para injetar o Secret criado no passo anterior
        secret:
          existingSecret: "authelia-users-secret"
          
        # Informa ao Authelia onde o arquivo injetado pelo Secret estará localizado dentro do container
        usersDatabase:
          path: /config/users_database.yml


  destination:
    server: https://kubernetes.default.svc
    namespace: authelia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true