apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd # Namespace onde o ArgoCD está instalado
spec:
  project: default
  source:
    # 1. A URL do repositório deve terminar na coleção 'immich-charts'
    repoURL: https://repo.helmforge.dev
    # CORREÇÃO: O nome do chart correto dentro do repositório
    chart: immich
    targetRevision: 1.2.9

    helm:
      values: |
        extraVolumes:
          - name: immich-uploads
            persistentVolumeClaim:
              claimName: immich-uploads
          - name: external-media
            persistentVolumeClaim:
              claimName: external-media
          - name: immich-config
            configMap:
              name: immich-config

        extraVolumeMounts:
          - name: external-media
            mountPath: /mnt/dados_vm/k8s
            readOnly: true
          - name: immich-config
            mountPath: /mnt/dados_vm/config/immich
            readOnly: true
          - name: immich-uploads
            mountPath: /mnt/dados_vm/upload/immich
            readOnly: false

        postgresql:
          enabled: true
        ingress:
          enabled: true 
          ingressClassName: "traefik"
          annotations: {}
          hosts:
            - host: immich.devtechdojo.com.br
              paths:
                - path: /
                  pathType: Prefix

  # Destino dentro do seu cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: immich # Namespace onde o Immich será implantado

  # Políticas de Sincronização
  syncPolicy:
    automated:
      prune: true     # Remove recursos antigos se você deletar do Git/Helm
      selfHeal: true  # Corrige desvios manuais feitos no cluster (drift)
    syncOptions:
      - CreateNamespace=true