apiVersion: v1
kind: Secret
metadata:
  name: authentik-bootstrap-credentials
  namespace: authentik
type: Opaque
stringData:
  AUTHENTIK_BOOTSTRAP_PASSWORD_HASH: "pbkdf2_sha256$1000000$xKKFuYtJEE27km09BD49x2$4+Z6j3utmouPF5mik0Z21L2P0og5IlmMmIJ46Tj3zCM="
  AUTHENTIK_BOOTSTRAP_TOKEN: "your-token-here"
  AUTHENTIK_BOOTSTRAP_EMAIL: "luckanadani@gmail.com"